{ ... }:

{
  # ┌─────────────────────────────────────┐
  # │      Display Manager (TUIGREET)     │
  # └─────────────────────────────────────┘
  services.greetd = {
    enable = true;
    vt = 3;
    settings = {
      default_session = {
        # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
        # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
        # command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
        command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd Hyprland";
      };
    };
  };
  environment.systemPackages = with pkgs; [
    greetd.tuigreet
  ];


  # ┌─────────────────┐
  # │      Audio      │
  # └─────────────────┘
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };


  # ┌─────────────────────┐
  # │      Bluetooth      │
  # └─────────────────────┘
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };
  services.blueman.enable = true;


  # ┌───────────────────┐
  # │      Network      │
  # └───────────────────┘
  services.networking = {
    networkmanager.enable = true;
    hostName = host;
    timeServers = options.networking.timeServers.default ++ [ "pool.ntp.org" ];
  };


  # ┌───────────────────┐
  # │     Printing      │
  # └───────────────────┘
  ipp-usb.enable = true;  # Internet Printing Protocol over usb
  services.printing = {
    enable = true;
    drivers = [
      # pkgs.hplipWithPlugin
    ];
  };


  # ┌───────────────────────────┐
  # │     Service Discovery     │
  # └───────────────────────────┘
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    openFirewall = true;
  };
}